name: PR Semgrep Scan

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  security-events: write

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Call Semgrep FastAPI scanner
        id: scan
        env:
          API_URL: ${{ secrets.SEMGREP_API_URL }}
        run: |
          PR_ID="${{ github.event.pull_request.number }}"
          COMMIT="${{ github.event.pull_request.head.sha }}"
          REPO="${{ github.event.pull_request.head.repo.clone_url }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          RESPONSE=$(curl -s -X POST "$API_URL/scan_pr" \
            -H "Content-Type: application/json" \
            -d "{\"pr_id\": \"$PR_ID\", \"repo_url\": \"$REPO\", \"commit_hash\": \"$COMMIT\", \"pr_url\": \"$PR_URL\"}")

          echo "$RESPONSE" > response.json

          SCAN_STATUS=$(jq -r '.status' response.json)
          SCAN_ID=$(jq -r '.scan_id' response.json)
          SARIF_FILE=$(jq -r '.sarif_file' response.json)

          echo "SCAN_STATUS=$SCAN_STATUS" >> $GITHUB_ENV
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
          echo "SARIF_FILE=$SARIF_FILE" >> $GITHUB_ENV

      - name: Wait for Approval
        if: env.SCAN_STATUS == 'blocked'
        env:
          API_URL: ${{ secrets.SEMGREP_API_URL }}
          SCAN_ID: ${{ env.SCAN_ID }}
        run: |
          echo "Waiting for security approval..."
          for i in {1..30}; do
            STATUS=$(curl -s "$API_URL/status/$SCAN_ID" | jq -r '.status')
            echo "Approval status: $STATUS"
            if [[ "$STATUS" == "approve" ]]; then
              echo "Approved! Proceeding..."
              exit 0
            elif [[ "$STATUS" == "reject" ]]; then
              echo "Rejected by security"
              exit 1
            fi
            sleep 20
          done
          echo "Timeout waiting for approval"
          exit 1

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.SARIF_FILE }}
        if: always()
